# Generated by Django 5.0.6 on 2024-07-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_id', models.IntegerField(default=0)),
                ('owner', models.CharField(default='GCGB', max_length=10)),
                ('type_id', models.IntegerField(default=1)),
                ('tag', models.CharField(max_length=20)),
                ('tag_color', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.IntegerField(default=1)),
                ('sire', models.CharField(blank=True, max_length=100, null=True)),
                ('dam', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=30)),
                ('is_admin', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('value', models.CharField(default='High', max_length=10)),
                ('unit_id', models.IntegerField()),
            ],
            options={
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.IntegerField(default=1)),
                ('sex', models.IntegerField(default=1)),
                ('unit_cost', models.IntegerField()),
                ('year', models.IntegerField()),
                ('year_market_unit_value', models.IntegerField(blank=True, null=True)),
                ('year_market_value', models.IntegerField(blank=True, null=True)),
                ('year_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('img', models.CharField(default='', max_length=300)),
            ],
            options={
                'db_table': 'viewer',
            },
        ),
    ]
