# Generated by Django 5.0.6 on 2024-07-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='farm_id',
        ),
        migrations.AddField(
            model_name='game',
            name='farm',
            field=models.IntegerField(default=1),
        ),
    ]
