# Generated by Django 5.0.6 on 2024-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('value', models.CharField(default='High', max_length=10)),
                ('unit_id', models.IntegerField()),
            ],
            options={
                'db_table': 'types',
            },
        ),
    ]
