# Generated by Django 5.0.6 on 2024-07-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='type_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='farm_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='type',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='type',
        ),
        migrations.AddField(
            model_name='game',
            name='farm',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='display.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='display.type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewer',
            name='viewer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='display.type'),
            preserve_default=False,
        ),
    ]
